name: build push and deploy image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-east-1
  AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}


jobs: 
  build: 
    runs-on: ubuntu-latest  # github runner
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: Aws cred config
        uses: Aws-actions/configure-aws-ctedential@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }} #OIDC
          AWS_region: ${{ env.AWS_REGION }}
      - name: Loging to ecr    
        uses: aws-actions/amazon-ecr-login@v1
            