name: build push and deploy image
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
permissions:
  id-token: write
  contents: read
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    env:
      AWS_REGION: us-east-1
      AWS_ROLE: ${{ secrets.AWS_ACTION_ROLE }}
      ECR_REPO_NAME: dev
      IMAGE_TAG: ${{github.run_number}}
 
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
 
      - name: AWS creds config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
 
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: build-and-push
        run:
            docker build -t ${{ steps.login.outputs.registry }}/${{env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}} .
            docker push ${{ steps.login.outputs.registry }}/${{env.ECR_REPO_NAME}}:${{env.IMAGE_TAG}}